var employees = [
    {
    "PID":"1001",
    "GroupName":"Piano",
    	"Name":"My Piano",
        "Price":"1000",
        "Quantity":"2",
        "Description":"This ia a Piano",
        "src": "Images/Sun.png",
    }, 
    {
        "PID":"1002",
        "GroupName":"Guitar",
        	"Name":"My Guitar",
            "Price":"2000",
            "Quantity":"3",
            "Description":"This ia a Piano",
            "src": "Images/Sun.png",
        }, 
        {
            "PID":"1003",
            "GroupName":"Accessories",
            	"Name":"My Acc",
                "Price":"2400",
                "Quantity":"10",
                "Description":"This ia a Piano",
                "src": "Images/Sun.png",
            }, 
            {
                "PID":"1004",
                "GroupName":"Guitar",
                	"Name":"My Guitar",
                    "Price":"2200",
                    "Quantity":"1",
                    "Description":"This ia a Piano",
                    "src": "Images/Sun.png",
                }, 
                {
                    "PID":"1005",
                    "GroupName":"Piano",
                    	"Name":"My Piano",
                        "Price":"1600",
                        "Quantity":"3",
                        "Description":"This ia a Piano",
                        "src": "Images/Sun.png",
                    }, 
                    {
                        "PID":"1006",
                        "GroupName":"Accessories",
                        	"Name":"My acc",
                            "Price":"3500",
                            "Quantity":"5",
                            "Description":"This ia a Piano",
                            "src": "Images/Sun.png",
                        }, 
];
